services:
  # Backend API Service
  - type: web
    name: dms-channel-backend
    runtime: node
    buildCommand: cd backend/backend && npm install && npm run build
    startCommand: cd backend/backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: FRONTEND_URL
        sync: false
      - key: WEBHOOK_BASE_URL
        sync: false
      - key: LOG_LEVEL
        value: info
      - key: MAX_CONCURRENT_CONNECTIONS
        value: 100
      - key: SESSION_TIMEOUT_MINUTES
        value: 30
    healthCheckPath: /api/health
    
  # Frontend Static Site
  - type: web
    name: dms-channel-frontend
    runtime: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_BASE_URL
        sync: false